source 'https://github.com/CocoaPods/Specs.git'
source 'https://github.com/artsy/Specs.git'

use_frameworks!

target 'Extraction_Example' do
  pod 'Extraction', :path => '../'

  if ENV['ARTSY_STAFF_MEMBER'] != nil || ENV['CI'] != nil
    pod 'Artsy+UIFonts', :git => "https://github.com/artsy/Artsy-UIFonts.git"
  else
    pod 'Artsy+UIFonts', :git => "https://github.com/artsy/Artsy-OSSUIFonts.git"
  end

# This is just to support ARSwitchView from Eigen. This needs to be sorted out
  # before trying to use Emission in Eigen.
  pod 'FLKAutoLayout', :git => 'https://github.com/floriankugler/FLKAutoLayout.git'

  target 'Extraction_Tests' do
    inherit! :search_paths

    pod 'Specta'
    pod 'Expecta'
    pod 'FBSnapshotTestCase/Core'
    pod 'Expecta+Snapshots'
  end
end
